### ISSUE TITLE
Tapping on current content screen doesn't close drawer

### ISSUE THREAD

**Issue by jsierles** [clearsightstudio/ProMotion-menu#51]
Not sure if this is an issue or if there's a way to implement it. When tapping on the menu item corresponding to the existing content view, I'd expect the menu to close and return to where it was. Currently it just stays open. Thanks!

**Comment by ryanlntn** [comment]
@jsierles That should be default behavior or you should be able to achieve that by adding `:tap_center` to the `to_hide` gesture recognizers. Something like:

```ruby
app_delegate.menu.to_hide = [:pan_center, :tap_center]
```

**Comment by ryanlntn** [comment]
You can achieve this by swapping out the center screen and hiding the menu.

```ruby
app_delegate.menu.center = MyContentScreen
app_delegate.menu.hide
```

**Comment by jsierles** [comment]
Thanks - that worked! Would this be good to include as default behavior?

**Comment by ryanlntn** [comment]
@jsierles I suppose we could add it to the example in the README. We don't provide a menu screen in this gem, just the drawer controller than can hold up to three screens. Setting up actions is therefore left to the user.
